name = "BayesianArena"
uuid = "9a958591-37c7-4438-b3c6-7968ddd9fc0d"
version = "0.1.0"
authors = ["Amirabbas Asadi"]

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DifferentialEquations = "7.17.0"
Distributions = "0.25.122"
LinearAlgebra = "1.12.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
